apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_ml
spec:
  replicas: 1  # Number of desired pods
  selector:
    matchLabels:
      app: flask_ml
  template:
    metadata:
      labels:
        app: flask_ml
    spec:
      containers:
        - name: flask_ml
          image: shivam424/flask:latest  # Your Docker image
          ports:
            - containerPort: 5000  # Port that your application listens on
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask_ml
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask_ml
