apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-compose-task
spec:
  workspaces:
      - name: source
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  steps:
    - name: run-docker-compose
      image: docker:latest  # Use a Docker image that has Docker CLI
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)/FairTrade  # Change to the directory where Docker Compose file is located
        docker-compose down
        docker-compose up -d
