apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-login-task
spec:
  workspaces:
    - name: source
  steps:
    - name: docker-login
      image: docker
      script: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: password
