
services:
  flask-ml:
    container_name: flask-ml
    image: shivam424/flask:latest
    ports:
      - "5001:5000"
    networks:
      - app_network

  django:
    container_name: django
    image: shivam424/django:latest
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/data
    depends_on:
      - flask-ml
    networks:
      - app_network

networks:
  app_network:

volumes:
  sqlite_data:
