apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fairtrade-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskSpec:
        steps:
          - name: clone
            image: alpine/git
            script: |
              git clone https://github.com/shivamjaiswal424/fairTradeWithTekton.git /workspace/shared-workspace
      workspaces:
        - name: shared-workspace

    - name: deploy-flask-ml
      taskRef:
        name: deploy-flask-ml-task
      runAfter:
        - clone-repo  # Run after cloning the repo
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy-django
      taskRef:
        name: deploy-django-task
      runAfter: 
        - deploy-flask-ml  # Django runs after Flask-ML
      workspaces:
        - name: source
          workspace: shared-workspace
