apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fairtrade-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: prometheus-storage  
    - name: grafana-storage     
    - name: docker-config

  tasks:
    # Step 1: Clone the repo
    - name: clone-repo
      taskRef:
        name: clone-task
      workspaces:
        - name: shared-workspace

    # Step 2: Build and push Django Docker image
    - name: build-and-push-django
      taskRef:
        name: build-and-push-django-task
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-config
          workspace: docker-config

    # Step 3: Build and push Flask-ML Docker image
    - name: build-and-push-flask-ml
      taskRef:
        name: build-and-push-flask-ml-task
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-config
          workspace: docker-config

    # Step 4: Deploy Django
    - name: deploy-django
      taskRef:
        name: deploy-django-task
      runAfter:
        - build-and-push-django
      workspaces:
        - name: source
          workspace: shared-workspace

    # Step 5: Deploy Flask-ML
    - name: deploy-flask-ml
      taskRef:
        name: deploy-flask-ml-task
      runAfter:
        - build-and-push-flask-ml
      workspaces:
        - name: source
          workspace: shared-workspace

    # Step 6: Run Prometheus
    - name: run-prometheus
      taskRef:
        name: run-prometheus
      runAfter:
        - deploy-django
        - deploy-flask-ml
      workspaces:
        - name: prometheus-storage
          workspace: prometheus-storage

    # Step 7: Run Grafana (new task)
    - name: run-grafana
      taskRef:
        name: run-grafana
      runAfter:
        - deploy-django
        - deploy-flask-ml
      workspaces:
        - name: grafana-storage
          workspace: grafana-storage
