apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prometheus-metrics-task
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: collect-metrics
      image: alpine
      script: |
        #!/bin/sh
        echo "Exposing Prometheus metrics"
        echo 'http_requests_total{method="post",code="200"} 1027' >> /metrics/metrics.prom
        cat /metrics/metrics.prom
      volumeMounts:
        - name: metrics-volume
          mountPath: /metrics
  volumes:
    - name: metrics-volume
      emptyDir: {}
