apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-flask-task
spec:
  workspaces:
    - name: source
  steps:
    - name: deploy-flask
      image: bitnami/kubectl:latest  # Use a Kubernetes CLI image
      command: ["kubectl"]
      args:
        - "create"
        - "deployment"
        - "flask-ml"
        - "--image=shivam424/flask:latest"
        - "--port=5000"
        - "--restart=Always"  # Use Always for deployment
        - "--overrides={\"apiVersion\":\"apps/v1\",\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"flask-ml\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"flask-ml\"}},\"spec\":{\"containers\":[{\"name\":\"flask-ml\",\"image\":\"shivam424/flask:latest\",\"ports\":[{\"containerPort\":5000}]}]}}}}"
