apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-django-task
spec:
  workspaces:
    - name: source
  steps:
    - name: deploy-django
      image: bitnami/kubectl:latest  # Use a Kubernetes CLI image
      command: ["kubectl"]
      args:
        - "create"
        - "deployment"
        - "django"
        - "--image=shivam424/django:latest"
        - "--port=8000"
        - "--restart=Always"  # Use Always for deployment
        - "--overrides={\"apiVersion\":\"apps/v1\",\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"django\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"django\"}},\"spec\":{\"containers\":[{\"name\":\"django\",\"image\":\"shivam424/django:latest\",\"ports\":[{\"containerPort\":8000}],\"volumeMounts\":[{\"name\":\"sqlite_data\",\"mountPath\":\"/data\"}]}],\"volumes\":[{\"name\":\"sqlite_data\",\"emptyDir\":{}}]}}}}"
