apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-service-monitor
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
